- name: Azure Arc-aktiverade Kubernetes
  href: index.yml
- name: Översikt
  items:
    - name: Om Azure Arc-aktiverade Kubernetes
      href: overview.md
    - name: Azure Arc-validerings program
      href: validation-program.md
- name: Snabbstarter
  items:
    - name: Ansluta ett kluster till Azure-bågen
      href: quickstart-connect-cluster.md
- name: Självstudier
  items:
    - name: Distribuera konfigurationer med GitOps
      href: tutorial-use-gitops-connected-cluster.md
    - name: Implementera CI/CD med GitOps
      href: tutorial-gitops-ci-cd.md
- name: Begrepp
  items:
    - name: Agent arkitektur
      href: conceptual-agent-architecture.md
    - name: Konfigurationer och GitOps
      href: conceptual-configurations.md
    - name: Kluster tillägg
      href: conceptual-extensions.md
    - name: Kluster anslutning
      href: conceptual-cluster-connect.md
    - name: Anpassade platser
      href: conceptual-custom-locations.md
    - name: Azure RBAC
      href: conceptual-azure-rbac.md
    - name: Vanliga frågor och svar
      href: faq.md
    - name: CI/CD-arbetsflöde med GitOps
      href: conceptual-gitops-ci-cd.md
- name: Anvisningar
  items:
    - name: Anslut kluster med tjänstens huvud namn
      href: create-onboarding-service-principal.md
    - name: Uppgradera agenter
      href: agent-upgrade.md
    - name: Scenarier
      items:
        - name: Distribuera Helm-diagram med GitOps
          href: use-gitops-with-helm.md
        - name: Framtvinga GitOps med hjälp av Azure Policy
          href: use-azure-policy.md
        - name: Distribuera och hantera kluster tillägg
          href: extensions.md
        - name: Övervaka med hjälp av Azure Monitor för containrar
          href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Framtvinga skydd av hot med Azure Defender
          href: ../../security-center/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Principer för åtkomstkontroll med hjälp av Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Anslut säkert till kluster från valfri plats
          href: cluster-connect.md
        - name: Använda Azure AD RBAC för verifierings kontroller
          href: azure-rbac.md
        - name: Skapa anpassade platser
          href: custom-locations.md
        - name: Distribuera IoT-arbetsbelastningar
          href: deploy-azure-iot-edge-workloads.md
    - name: Felsökning
      href: Troubleshooting.md
- name: Referens
  items:
    - name: Inbyggda Azure Policy-program
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Resurser
  items:
    - name: Planera för distribution
      href: plan-at-scale-deployment.md
    - name: Kom igång med Azure Arc
      href: 'https://azurearcjumpstart.io'